### ISSUE TITLE
Amiga DB23 RGBS

### ISSUE THREAD

**Issue by danko79** [jbilander/Amiga_db23_RGBS#1]
Hi, I don't know how to contact her, I need 3 DIY kits pcb with all caps and resistors of these are available?

**Comment by jbilander** [comment]
Hi,

Send me an email with your postal address and I can send you 3 pcs pcb + components and you can try it out. My email:

jorgen.bilander at gmail com

I recently made a cable with just using zero ohm resistors on the RGB lines, it worked well but I had to connect the shielding on the plugs as well to get rid of noise. Maybe the cable I used wasn't the best.

Regards, /JB
